apiVersion: v1
kind: Pod
metadata:
  name: nginx-naked-pod
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
---
# Deployment 1: The target for HPA
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-a
  template:
    metadata:
      labels:
        app: web-a
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
---
# Deployment 2: A secondary test app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-b
  template:
    metadata:
      labels:
        app: web-b
    spec:
      containers:
      - name: redis
        image: redis:alpine
---
# HPA: Scaling Deployment A based on CPU
# Deployment 1: The target for HPA
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-a
  template:
    metadata:
      labels:
        app: web-a
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
---
# Deployment 2: A secondary test app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-b
  template:
    metadata:
      labels:
        app: web-b
    spec:
      containers:
      - name: redis
        image: redis:alpine
---
# HPA: Scaling Deployment A based on CPU
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-a-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-server-a
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
# Persistent Volume (The physical storage)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data" # Ensure this directory exists on your node/host
---
# Persistent Volume Claim (The request for storage)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
